spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/banking
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
# Spring boot 2.6.2 version + Swagger 2.9.2 issue 해결을 위해 추가
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: create
      ## ddl-auto : update
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

